FROM debian:9-slim '?\'\=
'=[p;'/
= Configure locales (for Click python module)
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

RUN apt-get update && apt-get install -y apache2 \
    libapache2-mod-wsgi-py3 \
    python3 \
    python3-pip \
 && apt-get clean \
 && apt-get autoremove \
&& rm -rf /var/lib/apt/lists/*

# Copy Apache2 configs and enable API
COPY ./docker/app.conf /etc/apache2/sites-available/app.conf
RUN a2dissite 000-default.conf
RUN a2ensite app

# Need for foreground to work
RUN a2enmod lbmethod_byrequests
RUN a2enmod ssl

# Copy app
COPY ./ /opt/app/

WORKDIR /opt/app

# Install requirements
RUN pip3 install -r requirements.txt

EXPOSE 80

CMD apachectl -D FOREGROUND
